# Generated by Django 4.1.7 on 2023-06-21 07:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inside_default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidedefault',
            name='content_rich_2',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
