# Generated by Django 4.1.7 on 2023-06-25 15:35

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('inside_default', '0002_insidedefault_content_rich_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='insidedefault',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.blocks.RawHTMLBlock())], default=[('paragraph', ''), ('image', ''), ('html', '')], use_json_field=True),
        ),
        migrations.AddField(
            model_name='insidedefault',
            name='image_banner',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
