# Generated by Django 4.1.7 on 2023-06-25 16:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('inside_default', '0003_insidedefault_body_insidedefault_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidedefault',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.blocks.RawHTMLBlock())], use_json_field=True),
        ),
    ]
