# Generated by Django 4.1.7 on 2023-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside_default', '0004_alter_insidedefault_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidedefault',
            name='image_banner',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
