# Generated by Django 4.1.7 on 2023-06-25 16:53

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('inside_default', '0005_alter_insidedefault_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidedefault',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.blocks.RawHTMLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='insidedefault',
            name='image_banner',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
