# Generated by Django 4.1.7 on 2023-07-24 11:55

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inside_default', '0006_alter_insidedefault_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidedefault',
            name='content_rich_1',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Sidebar List'),
        ),
        migrations.AlterField(
            model_name='insidedefault',
            name='content_rich_2',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Sidebar Content'),
        ),
        migrations.AlterField(
            model_name='insidedefault',
            name='image_banner',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Page Banner'),
        ),
    ]
